version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ${PWD}/homework_3/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "8080:80"
    environment:
     - NGINX_PORT=80

  django:
    build:
      context: ./distance_learning_system
    container_name: app_homework_3
    volumes:
      - ${PWD}/homework_3/distance_learning_system:/app
    ports:
      - "8000:8000"
    restart: unless-stopped
    entrypoint: python manage.py runserver 0.0.0.0:8000