version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ${PWD}/homework_2/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/homework_2/nginx/public/:/usr/share/nginx/
    ports:
     - "8080:80"
    environment:
     - NGINX_PORT=80
  app:
    build:
      context: ./app
    container_name: app_homework_2
    volumes:
      - ${PWD}/homework_2/app:/app
    ports:
      - "8000:8000"