# Generated by Django 4.0 on 2024-04-25 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID курса')),
                ('name', models.CharField(max_length=100, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('paid', models.BooleanField(verbose_name='Платный курс')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID занятия')),
                ('theme', models.CharField(max_length=150, verbose_name='Тема занятия')),
                ('material', models.TextField(verbose_name='Материал занятия')),
                ('time', models.IntegerField(verbose_name='Продолжительность занятия (мин)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
    ]
